[2025-06-12T19:53:18.661+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-06-12T19:53:18.694+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: md_pipeline_fspo.bronze_ingest_failures manual__2025-06-12T19:53:18.143935+00:00 [queued]>
[2025-06-12T19:53:18.705+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: md_pipeline_fspo.bronze_ingest_failures manual__2025-06-12T19:53:18.143935+00:00 [queued]>
[2025-06-12T19:53:18.712+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-06-12T19:53:18.730+0000] {taskinstance.py:2889} INFO - Executing <Task(SparkSubmitOperator): bronze_ingest_failures> on 2025-06-12 19:53:18.143935+00:00
[2025-06-12T19:53:18.740+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=177) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-12T19:53:18.742+0000] {standard_task_runner.py:72} INFO - Started process 178 to run task
[2025-06-12T19:53:18.740+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'md_pipeline_fspo', 'bronze_ingest_failures', 'manual__2025-06-12T19:53:18.143935+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/load-failures.py', '--cfg-path', '/tmp/tmp9jz3bybu']
[2025-06-12T19:53:18.745+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask bronze_ingest_failures
[2025-06-12T19:53:18.774+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-12T19:53:18.846+0000] {task_command.py:467} INFO - Running <TaskInstance: md_pipeline_fspo.bronze_ingest_failures manual__2025-06-12T19:53:18.143935+00:00 [running]> on host a42b6fdada18
[2025-06-12T19:53:19.090+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='md_pipeline_fspo' AIRFLOW_CTX_TASK_ID='bronze_ingest_failures' AIRFLOW_CTX_EXECUTION_DATE='2025-06-12T19:53:18.143935+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-12T19:53:18.143935+00:00'
[2025-06-12T19:53:19.093+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-06-12T19:53:19.220+0000] {base.py:84} INFO - Retrieving connection 'spark_default'
[2025-06-12T19:53:19.222+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master yarn --conf spark.jars=/path/to/postgres-jdbc.jar --name bronze_ingest_failures --queue root.default scripts/ingest_failures.py --target-table bronze.equipment_failure_sensors
[2025-06-12T19:53:19.229+0000] {spark_submit.py:644} INFO - /home/airflow/.local/bin/spark-submit: line 27: /usr/local/lib/python3.10/site-packages/pyspark/bin/spark-class: No such file or directory
[2025-06-12T19:53:19.250+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 197, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 566, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.jars=/path/to/postgres-jdbc.jar --name bronze_ingest_failures --queue root.default scripts/ingest_failures.py --target-table bronze.equipment_failure_sensors. Error code is: 127.
[2025-06-12T19:53:19.263+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=md_pipeline_fspo, task_id=bronze_ingest_failures, run_id=manual__2025-06-12T19:53:18.143935+00:00, execution_date=20250612T195318, start_date=20250612T195318, end_date=20250612T195319
[2025-06-12T19:53:19.285+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-06-12T19:53:19.286+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 17 for task bronze_ingest_failures (Cannot execute: spark-submit --master yarn --conf spark.jars=/path/to/postgres-jdbc.jar --name bronze_ingest_failures --queue root.default scripts/ingest_failures.py --target-table bronze.equipment_failure_sensors. Error code is: 127.; 178)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 197, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 566, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --conf spark.jars=/path/to/postgres-jdbc.jar --name bronze_ingest_failures --queue root.default scripts/ingest_failures.py --target-table bronze.equipment_failure_sensors. Error code is: 127.
[2025-06-12T19:53:19.321+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-06-12T19:53:19.361+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-12T19:53:19.369+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
